// Automatically generated by astro-icon
// dc87e1303a4e7bc8b411af41358bdd6db7ac3b704f0bc245f1489f1aa38cc378

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "donation"
		| "next"
		| "open"
		| "public"
		| "test";
}