backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "src/assets" # Media files will be stored in the repo under static/images/uploads
public_folder: "../../assets" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Bild", name: "heroImage", widget: "image"}
      - {label: "Autor momentan nicht vergeben", name: "author", widget: "string"}
      - {label: "Datum", name: "pubDatetime", widget: "datetime"}
      - {label: "Vorgeschlagen auf der Startseite", name: "featured", widget: "boolean"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Beschreibung", name: "description", widget: "string"}
      - {label: "Artikel", name: "body", widget: "markdown"}

